### Starting learning NumPy

In [29]:
print("Hello World")

Hello World


In [30]:
import numpy as np


### Creating array from list

In [31]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


### List vs NumPy Array

In [32]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.06426572799682617

 Numpy operation time:  0.004145145416259766


### Creating Array from Scratch


In [33]:
random = np.random.random((2,2))
print("Random array:", random)

sequence = np.arange(0, 11, 2)
print("Sequence array: \n", sequence)

zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

ones = np.ones((2, 3))
print("ones array: \n", ones)

full = np.full((2, 2), 7)
print("full array: \n", full)


Random array: [[0.86659453 0.23784113]
 [0.21518195 0.05916265]]
Sequence array: 
 [ 0  2  4  6  8 10]
zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]


### Vector,Matrix and Tensor

In [34]:
vector = np.array([1,2,3])
print("Vector: ", vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("Tensor: ", tensor)


Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [35]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])
print("Shape :", arr.shape)
print("Dimension :", arr.ndim)
print("Size :", arr.size)
print("DataType :", arr.dtype)

Shape : (2, 3)
Dimension : 2
Size : 6
DataType : int64


### Array Reshaping

In [36]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)
                                          #Flatten vs Ravel in numpy: The main difference between flatten and ravel is that flatten returns a copy of the original array, while ravel returns a view of the original array whenever possible. This means that if you modify the flattened array, it will not affect the original array, but if you modify the raveled array, it may affect the original array if it is a view.
# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### NumPy Array Operations

In [37]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing: ",arr[2:7])
print("Slicing with step: ", arr[1:8:2])
print("Slicing with negative step: ", arr[8:1:-2])


Basic slicing:  [3 4 5 6 7]
Slicing with step:  [2 4 6 8]
Slicing with negative step:  [9 7 5 3]


In [38]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire column: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire column:  [2 5 8]


### 2D Array Slicing Operations

In [39]:
#   arr[row_start:row_stop:row_step,col_start:col_stop:col_step]              This is the general syntax for slicing a 2D array in NumPy. You can specify the start, stop, and    step for both rows and columns to extract a specific subarray from the original array.

arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print("Original array:", arr)

# Single element
print("Element at [1, 2]:", arr[1, 2])       # 70

# Row
print("First row:", arr[0, :])       # [10 20 30 40]

# Column
print("Second column:", arr[:, 1])       # [20 60 100]

# First 2 rows
print("First 2 rows:", arr[:2, :])

# First 2 columns
print("First 2 columns:", arr[:, :2])

# Part of array
print("Part of array:", arr[0:2, 1:3])

# Last 2 rows
print("Last 2 rows:", arr[-2:, :])

# Last 2 columns
print("Last 2 columns:", arr[:, -2:])

# Every 2nd row
print("Every 2nd row:", arr[::2, :])

# Every 2nd column
print("Every 2nd column:", arr[:, ::2])

# Reverse rows
print("Reverse rows:", arr[::-1, :])

# Reverse columns
print("Reverse columns:", arr[:, ::-1])

Original array: [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Element at [1, 2]: 70
First row: [10 20 30 40]
Second column: [ 20  60 100]
First 2 rows: [[10 20 30 40]
 [50 60 70 80]]
First 2 columns: [[ 10  20]
 [ 50  60]
 [ 90 100]]
Part of array: [[20 30]
 [60 70]]
Last 2 rows: [[ 50  60  70  80]
 [ 90 100 110 120]]
Last 2 columns: [[ 30  40]
 [ 70  80]
 [110 120]]
Every 2nd row: [[ 10  20  30  40]
 [ 90 100 110 120]]
Every 2nd column: [[ 10  30]
 [ 50  70]
 [ 90 110]]
Reverse rows: [[ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]
Reverse columns: [[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]]


### Sorting

In [40]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Unsorted 2D array: ", arr_2d_unsorted)
print("Sorted 2D array along columns: ", np.sort(arr_2d_unsorted, axis=0))
print("Sorted 2D array along rows: ", np.sort(arr_2d_unsorted, axis=1))
print("Sorted 2D array flattened: ", np.sort(arr_2d_unsorted, axis=None))

Sorted array:  [1 1 2 3 4 5 5 6 9]
Unsorted 2D array:  [[3 1]
 [1 2]
 [2 3]]
Sorted 2D array along columns:  [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array along rows:  [[1 3]
 [1 2]
 [2 3]]
Sorted 2D array flattened:  [1 1 2 2 3 3]


### Filter

In [41]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers%2 == 0]
print("Even Numbers: ", even_number)

Even Numbers:  [ 2  4  6  8 10]


### Filter with Mask

In [42]:
mask = numbers>5
print("Numbers greater than 5: ", numbers[mask])

Numbers greater than 5:  [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [43]:
indices = np.array([0,2,4])
print(numbers[indices])

where_result = np.where(numbers>5)
print(where_result) #It stores the indices of the elements that satisfy the condition (numbers > 5).
print("Numbers greater than 5 using where: ", numbers[where_result])


[1 3 5]
(array([5, 6, 7, 8, 9]),)
Numbers greater than 5 using where:  [ 6  7  8  9 10]


In [44]:
condition_array = np.where(numbers > 5, numbers*4, numbers) #It is like if else condition, if numbers>5 then numbers*4 else numbers
print("Condition array: ", condition_array)
condition_array = np.where(numbers > 5, "true", "false") #It is like if else condition, if numbers>5 then true else false
print("Condition array: ", condition_array)

Condition array:  [ 1  2  3  4  5 24 28 32 36 40]
Condition array:  ['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


### Adding and removing data

In [45]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
add = arr1 + arr2
print("Addition of two arrays: ", add)

combined = np.concatenate((arr1, arr2)) # It will combine the two arrays into a single array. The resulting array will have the elements of arr1 followed by the elements of arr2.
print("Concatenated array: ", combined)

arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2) #It will delete the element at index 2 (which is 3) from the array. The resulting array will be [1, 2, 4, 5].
print("Deleted array: ", deleted)

Addition of two arrays:  [5 7 9]
Concatenated array:  [1 2 3 4 5 6]
Deleted array:  [1 2 4 5]


### Array Compatibility

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("Compatibility shapes: ",a.shape == b.shape == c.shape) #It will check if the shapes of the three arrays are compatible for element-wise operations. In this case, all three arrays have the same shape (1D arrays with 3 elements), so the result will be True.


Compatibility shapes:  True


In [47]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) #It will vertically stack the new_row below the original array. The resulting array will be [[1, 2], [3, 4], [5, 6]].
print("Original array: ", original)
print("Array with new row: ", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) #It will horizontally stack the new_col to the right of the original array. The resulting array will be [[1, 2, 7], [3, 4, 8]].
print("Array with new column: ", with_new_col)

Original array:  [[1 2]
 [3 4]]
Array with new row:  [[1 2]
 [3 4]
 [5 6]]
Array with new column:  [[1 2 7]
 [3 4 8]]


### Some Vector Operations

In [48]:
vector1 = np.array([1, 2, 3, 4, 5])
vector2 = np.array([6, 7, 8, 9, 10])

print("Vector addition: ", vector1 + vector2)

print("\nMultiplication vector", vector1 * vector2)

print("\nDot Product", np.dot(vector1, vector2))

angle = np.arccos(np.dot(vector1, vector2) / (np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("Angle between vectors (in radians):", angle)
print("Angle between vectors (in degrees):", np.degrees(angle))

Vector addition:  [ 7  9 11 13 15]

Multiplication vector [ 6 14 24 36 50]

Dot Product 130
Angle between vectors (in radians): 0.26554161733900966
Angle between vectors (in degrees): 15.214413958603176


In [50]:
restaurant_types = np.array(['biryani', 'chinese', 'pizza', 'burger', 'cafe'])  #Vectorized operations allow you to apply a function to each element of an  array without the need for explicit loops. In this case, we are using np.vectorize to create a vectorized version of the str.upper function, which converts strings to uppercase.
vectorized_upper = np.vectorize(str.upper)
print("Vectorized Upper", vectorized_upper(restaurant_types))

Vectorized Upper ['BIRYANI' 'CHINESE' 'PIZZA' 'BURGER' 'CAFE']


### Aggregations: `sum()`, `mean()`, `min()`, `max()`  

In [51]:

marks = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [90, 95, 80]
])

print("Marks:")
print(marks)

# Sum
print("Total:", np.sum(marks))

# Sum of each column
print("Column sum:", np.sum(marks, axis=0))

# Sum of each row
print("Row sum:", np.sum(marks, axis=1))

# Mean of each column
print("Column average:", np.mean(marks, axis=0))

# Mean of each row
print("Row average:", np.mean(marks, axis=1))

# Minimum of each column
print("Column minimum:", np.min(marks, axis=0))

# Maximum of each row
print("Row maximum:", np.max(marks, axis=1))

Marks:
[[80 90 70]
 [60 75 85]
 [90 95 80]]
Total: 725
Column sum: [230 260 235]
Row sum: [240 220 265]
Column average: [76.66666667 86.66666667 78.33333333]
Row average: [80.         73.33333333 88.33333333]
Column minimum: [60 75 70]
Row maximum: [90 85 95]


### Basic Arithmetc Operations

In [ ]:

a = np.array([10, 20, 30])
b = np.array([2, 5, 10])

print(a + b)   
print(a - b)   
print(a * b)   
print(a / b)   
print(a ** b)  # Power
print(a % b)   # Modulus

[12 25 40]
[ 8 15 20]
[ 20 100 300]
[5. 4. 3.]
[            100         3200000 590490000000000]
[0 0 0]


In [54]:
a = np.array([10, 20, 30])    #You can also perform operations with a single number.

print(a + 5) #Broadcasting in NumPy allows you to perform operations on arrays of different shapes and sizes. In this case, the scalar value 5 broadcasted to match the shape of the array a, allowing for element-wise addition. The result is a new array where 5 has been added to each element of a.
print(a - 5)   
print(a * 5)   
print(a / 5)   

[15 25 35]
[ 5 15 25]
[ 50 100 150]
[2. 4. 6.]
