In [18]:
import numpy as np

## Practice With Real World Data

In [19]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("=== Zomato sales analysis ===")

  

=== Zomato sales analysis ===


In [20]:
#Total sales per year
total_sales_per_year = np.sum(sales_data[:, 1:], axis=0)
print("Total sales per year:", total_sales_per_year)

#Minimum and maximum sales per restaurant
min_sales_per_restaurant = np.min(sales_data[:, 1:], axis=1)
max_sales_per_restaurant = np.max(sales_data[:, 1:], axis=1)
print("Minimum sales per restaurant:", min_sales_per_restaurant)
print("Maximum sales per restaurant:", max_sales_per_restaurant)

#Maximum Sales per year
max_sales_per_year = np.max(sales_data[:, 1:], axis=0)
print("Maximum sales per year:", max_sales_per_year)

#Average sales per restaurant
average_sales_per_restaurant = np.mean(sales_data[:, 1:], axis=1)
print("Average sales per restaurant:", average_sales_per_restaurant)

#Cumulative sales across all restaurants 
cumulative_sales = np.cumsum(sales_data[:, 1:], axis=1)
print("Cumulative sales across all restaurants:", cumulative_sales)



Total sales per year: [ 810000  945000 1085000 1240000]
Minimum sales per restaurant: [150000 120000 200000 180000 160000]
Maximum sales per restaurant: [250000 190000 300000 270000 230000]
Maximum sales per year: [200000 230000 260000 300000]
Average sales per restaurant: [200000. 152500. 247500. 225000. 195000.]
Cumulative sales across all restaurants: [[150000 330000 550000 800000]
 [120000 260000 420000 610000]
 [200000 430000 690000 990000]
 [180000 390000 630000 900000]
 [160000 345000 550000 780000]]


## General Questions

In [21]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

#### Get the shape of the matrix.

In [22]:
print(data.shape)

(5, 3)


#### Find the average age of students.

In [23]:
avgAge =np.mean(data[:,0])
print("Average Age of Students:", avgAge)

Average Age of Students: 18.4


#### Extract Math marks of all students.

In [24]:
mathmarks = np.array(data[:,1])
print(mathmarks)

[85 92 76 65 90]


#### Find the highest Science mark.

In [25]:
highsci = np.max(data[:,2])
print("Highest Science Marks:", highsci)

Highest Science Marks: 95


#### Get details of the student who scored more than 90 in Math.

In [31]:
moreThan90 = data[data[:,1] > 90]
print(data[:,1]>90)
print("Students with Math Marks greater than 90:", moreThan90)

[False  True False False False]
Students with Math Marks greater than 90: [[19 92 88]]


#### Increase Math marks of all students by 5.

In [27]:
newMathMarks = np.array(data[:,1])+5
print("New Math Marks after adding 5:", newMathMarks)

New Math Marks after adding 5: [90 97 81 70 95]


#### Find how many students are younger than 19.

In [35]:
syoungerThan19 = data[data[:,0]<19]
print("Students younger than 19:", len(syoungerThan19))

Students younger than 19: 3


#### Calculate the average marks in each subject (column-wise mean).

In [29]:
aVgMarks = np.mean(data[:,1:3], axis=0)
print("Average Marks in each subject:", aVgMarks)

Average Marks in each subject: [81.6 83.2]


#### Get data of students who scored at least 80 in both subjects.

In [36]:
sb80 = data[(data[:,1] >= 80) & (data[:,2] >= 80)]
print("Students with at least 80 marks in both subjects:", sb80)

Students with at least 80 marks in both subjects: [[19 92 88]
 [20 90 85]]


#### Replace all Science marks < 75 with 0.

In [37]:
 data[:,2][data[:,2] < 75] = 0
 print("Science marks less than 75 set to 0:", data)

Science marks less than 75 set to 0: [[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]
